### ISSUE TITLE
Don't work with js-controller

### ISSUE THREAD

**Issue by pmueller99** [dan1-de/ioBroker.anelhut#35]
**Describe the bug**  
After upgrading to js-controller 5.09 from 4.06 the adapter dont start anymore

**Screenshots & Logfiles**  
2023-07-28 22:39:47.955 - error: anelhut.0 (3447) undefined is not a valid state value
2023-07-28 22:39:47.956 - error: anelhut.0 (3447) Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().
2023-07-28 22:39:47.956 - error: anelhut.0 (3447) unhandled promise rejection: undefined is not a valid state value
2023-07-28 22:39:47.956 - error: anelhut.0 (3447) Error: undefined is not a valid state value
at Object.maybeCallbackWithError (/opt/iobroker/node_modules/@iobroker/js-controller-common/build/lib/common/maybeCallback.js:35:17)
at Anelhut._setState (/opt/iobroker/node_modules/@iobroker/js-controller-adapter/build/lib/adapter/adapter.js:5386:49)
at Anelhut.setState (/opt/iobroker/node_modules/@iobroker/js-controller-adapter/build/lib/adapter/adapter.js:5347:21)
at Anelhut.setDeviceProperties (/opt/iobroker/node_modules/iobroker.anelhut/build/main.js:211:14)
at async Anelhut.UpdateHutData (/opt/iobroker/node_modules/iobroker.anelhut/build/main.js:107:9)

**Versions:**  
 - Adapter version: <adapter-version>
 - JS-Controller version: 5.0.9
 - Node version: v16.15.1
 - Operating system: ubuntu 22.04

**Comment by dan1-de** [comment]
Hi,
just st saw the ticket today 
I'll check this.

**Comment by dan1-de** [comment]
Hi @pmueller99, 

I implemented a fix for this.
You can install the new adapter version from this github url please and give me feedback:
https://github.com/dan1-de/ioBroker.anelhut/tarball/dev

Version is 1.0.15.

Br,
Daniel

**Comment by pmueller99** [comment]
Hi dan1-de,

seems to work fine for me. Thanks a lot

**Comment by dan1-de** [comment]
Perfekt. I'll close the ticket and push the new adapter version to the stable repo.
